<?php
function joy_preprocess_menu_local_task(&$variables)
{
    $variables['link']['#options']['attributes']['class'][] = 'font-sans';
    $variables['link']['#options']['attributes']['class'][] = 'btn';
    $variables['link']['#options']['attributes']['class'][] = 'btn-sm';
    $variables['link']['#options']['attributes']['class'][] = 'btn-outline-primary';
    $variables['link']['#options']['attributes']['role'][] = 'button';
}
